app/accounts/urls.py
from django.conf.urls import url

from . import views
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^users/$', views.users, name='users'),
    url(r'^users/(?P<id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^users/add/$', views.add, name='add'),
    url(r'^users/(?P<id>[0-9]+)/edit/$', views.edit, name='edit'),
    url(r'^users/(?P<id>[0-9]+)/active/$', views.active, name='active'),
    url(r'^users/(?P<id>[0-9]+)/desactive/$', views.desactive, name='desactive'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit/$', views.profile_edit, name='profile_edit'),
]

app/docs/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views
urlpatterns = [
    url(r'^$', RedirectView.as_view(url='latest/', permanent=False), name='index'),
    url(r'^latest/$', views.latest, name='latest'),
    url(r'^documentations/$', views.docs, name='docs'),
    url(r'^documentations/add/$', views.doc_add, name='doc_add'),
    url(r'^documentations/(?P<id>[0-9]+)/$', views.doc_detail, name='doc_detail'),
    url(r'^documentations/(?P<id>[0-9]+)/edit/$', views.doc_edit, name='doc_edit'),
    url(r'^documentations/(?P<id>[0-9]+)/delete/$', views.doc_delete, name='doc_delete'),
    url(r'^keywords/$', views.words, name='words'),
    url(r'^keywords/(?P<id>[0-9]+)/$', views.word_detail, name='word_detail'),
    url(r'^keywords/(?P<id>[0-9]+)/edit/$', views.word_edit, name='word_edit'),
    url(r'^keywords/(?P<id>[0-9]+)/delete/$', views.word_delete, name='word_delete'),
]

app/doksys/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^accounts/', include("accounts.urls")),
    url(r'^', include("docs.urls"))
]

app/accounts/models.py
from django.db import models

# Create your models here.

app/docs/models.py
from django.db import models
from django.contrib.auth.models import User

class Keyword(models.Model):
    title = models.CharField(max_length=30, unique=True)
    url = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('date published')

class Document(models.Model):
    title = models.CharField(max_length=200, unique=True)
    url = models.URLField(max_length=200, unique=True)
    content = models.TextField()
    keywords = models.ManyToManyField(Keyword)
    user = models.ForeignKey(User)
    pub_date = models.DateTimeField('date published')

class History(models.Model):
    document = models.ForeignKey(Document)
    action = models.CharField(max_length=32)
    user = models.ForeignKey(User)
    pub_date = models.DateTimeField('date published')

app/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

def login(request):
    msg = ''
    if request.method == "POST":
        user = authenticate(username=request.POST["username"], password=request.POST["password"])
        if user is not None:
            if user.is_active:
                auth_login(request, user)
                msg = 'Login Realizado com sucesso!'
                return redirect('/')
            else:
                msg = "A conta está desabilitada."
        else:
            msg = "Usuário ou Senha estão incorretos."
    context = {
        'layout': 'materialize/index.html',
        'msg': msg
    }
    return render(request, 'login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('/')

@login_required
def users(request):
    if not request.user.is_superuser:
        return redirect('/accounts/profile/')
    context = {
        'layout': 'materialize/index.html',
        'users': User.objects.order_by('first_name'),
        'breadcumb': [
            {'title' : 'Contas', 'url': 'accounts/'}
        ]
    }
    return render(request, 'users.html', context)

@login_required
def detail(request, id):
    if not request.user.is_superuser:
        return redirect('/accounts/profile/')
    user = get_object_or_404(User, pk=id)
    context = {
        'layout': 'materialize/index.html',
        'user': user,
        'breadcumb': [
            {'title' : 'Contas', 'url': 'accounts/'},
            {'title' : 'Perfis', 'url': 'accounts/users/'},
            {'title' : user.first_name + ' ' + user.last_name, 'url': 'accounts/users/' + str(user.id) + '/'},
        ]
    }
    return render(request, 'detail.html', context)

@login_required
def add(request):
    if not request.user.is_superuser:
        return redirect('/accounts/profile/')
    if request.method == "POST":
        user = User.objects.create_user(request.POST.get("username"), request.POST.get("email"), request.POST.get("password"))
        user.first_name = request.POST.get("first_name")
        user.last_name = request.POST.get("last_name")
        if(request.POST.get('is_superuser')):
            user.is_superuser = True
        user.save()
        return redirect('/accounts/users/')
    context = {
        'layout': 'materialize/index.html',
        'breadcumb': [
            {'title' : 'Contas', 'url': 'accounts/'},
            {'title' : 'Perfis', 'url': 'accounts/users/'},
            {'title' : 'Adicionar', 'url': 'accounts/users/add/'},
        ]
    }
    return render(request, 'add.html', context)

@login_required
def edit(request, id):
    if not request.user.is_superuser:
        return redirect('/accounts/profile/')
    user = User.objects.get(pk=id)
    if request.method == "POST":
        User.objects.filter(pk=id).update(first_name=request.POST.get("first_name"),last_name=request.POST.get("last_name"),email=request.POST.get("email"), username=request.POST.get("username"))
        user = User.objects.get(pk=id)
        if request.POST.get("password"):
            user.set_password(request.POST.get("password"))
        if(request.POST.get('is_superuser')):
            user.is_superuser = True
        else:
            user.is_superuser = False
        user.save()
        return redirect('/accounts/users/')
    context = {
        'layout': 'materialize/index.html',
        'user': user,
        'breadcumb': [
            {'title' : 'Contas', 'url': 'accounts/'},
            {'title' : 'Perfis', 'url': 'accounts/users/'},
            {'title' : user.first_name + ' ' + user.last_name, 'url': 'accounts/users/' + str(user.id) + '/'},
            {'title' : 'Editar', 'url': 'accounts/users/' + str(user.id) + '/edit/'},
        ]
    }
    return render(request, 'edit.html', context)

@login_required
def delete(request, id):
    if not request.user.is_superuser:
        return redirect('/accounts/profile/')
    user = User.objects.get(pk=id)
    user.delete()
    return redirect('/accounts/users/')

@login_required
def active(request, id):
    if not request.user.is_superuser:
        return redirect('/accounts/profile/')
    user = User.objects.get(pk=id)
    user.is_active = True
    user.save()
    return redirect('/accounts/users/')

@login_required
def desactive(request, id):
    if not request.user.is_superuser:
        return redirect('/accounts/profile/')
    user = User.objects.get(pk=id)
    user.is_active = False
    user.save()
    return redirect('/accounts/users/')

@login_required
def profile(request):
    user = get_object_or_404(User, pk=request.user.id)
    context = {
        'layout': 'materialize/index.html',
        'user': user,
        'breadcumb': [
            {'title' : 'Contas', 'url': 'accounts/'},
            {'title' : 'Perfis', 'url': 'accounts/users/'},
            {'title' : user.first_name + ' ' + user.last_name, 'url': 'accounts/users/' + str(user.id) + '/'},
        ]
    }
    return render(request, 'profile.html', context)

@login_required
def profile_edit(request):
    if request.method == "POST":
        User.objects.filter(pk=request.user.id).update(first_name=request.POST.get("first_name"),last_name=request.POST.get("last_name"),email=request.POST.get("email"), username=request.POST.get("username"))
        user = User.objects.get(pk=request.user.id)
        if request.POST.get("password"):
            user.set_password(request.POST.get("password"))
        if(request.POST.get('is_superuser')):
            user.is_superuser = True
        else:
            user.is_superuser = False
        user.save()
        return redirect('/accounts/users/')
    user = User.objects.get(pk=request.user.id)
    context = {
        'layout': 'materialize/index.html',
        'user': user,
        'breadcumb': [
            {'title' : 'Contas', 'url': 'accounts/'},
            {'title' : 'Perfis', 'url': 'accounts/users/'},
            {'title' : user.first_name + ' ' + user.last_name, 'url': 'accounts/users/' + str(user.id) + '/'},
            {'title' : 'Editar', 'url': 'accounts/users/' + str(user.id) + '/edit/'},
        ]
    }
    return render(request, 'profile_edit.html', context)

app/accounts/templates/add.html
{% extends layout %}
{% block content %}

<form method="POST">
  {% csrf_token %}

  <div class="row">
    <button type="submit" class="waves-effect waves-light btn-large col s12">
      Salvar
    </button>
  </div>

  <div class="row card-panel">
    <h5 class="col s12 center-align">Informações do Funcionário</h5>
    <div class="input-field col s12 m4">
      <input id="first_name" name="first_name" type="text" class="validate">
      <label for="first_name">Primeiro Nome</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="last_name" name="last_name" type="text" class="validate">
      <label for="last_name">Último Nome</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="email" name="email" type="text" class="validate">
      <label for="email">Email</label>
    </div>
  </div>
  <div class="row card-panel">
    <h5 class="col s12 center-align">Acessos do Funcionário</h5>
    <div class="input-field col s12 m4">
      <input id="username" name="username" type="text" class="validate">
      <label for="username">Usuário</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="password" name="password" type="password" class="validate">
      <label for="password">Senha</label>
    </div>
    <div class="input-field col s12 m4">
      <p>
        <input id="is_superuser" name="is_superuser" type="checkbox" />
        <label for="is_superuser">Super Usuário</label>
      </p>
    </div>
  </div>
</form>

{% endblock content %}

app/accounts/templates/detail.html
{% extends layout %}
{% block content %}

<div class="row">
  <div class="col s6">
    <a class="waves-effect waves-light btn-large green col s12" href="accounts/users/{{user.id}}/edit/">
      Editar Usuário
    </a>
  </div>
  <div class="col s6">
    {% if user.is_active %}
    <a class="waves-effect waves-light btn-large red col s12"{% if request.user.is_superuser %} href="#confirm-desactive"{% else %}disabled{% endif %}>
      Desativar Usuário
    </a>
    {% else %}
    <a class="waves-effect waves-light btn-large blue col s12"{% if request.user.is_superuser %} href="#confirm-active"{% else %}disabled{% endif %}>
      Ativar Usuário
    </a>
    {% endif %}
  </div>
</div>

<div id="confirm-active" class="modal">
  <div class="modal-content">
    <h4>Ativar Usuário</h4>
    <p>Deseja Reativar o usuário:<br/><strong>{{user.first_name}}&nbsp;{{user.last_name}}</strong></p>
    <p>Ao reativar o usuário poderá acessar o sistema.</p>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
    <a href="accounts/users/{{user.id}}/active/" class="waves-effect waves-green btn-flat">Ativar</a>
  </div>
</div>

<div id="confirm-desactive" class="modal">
  <div class="modal-content">
    <h4>Desativar Usuário</h4>
    <p>Deseja mesmo desativar o usuário:<br/><strong>{{user.first_name}}&nbsp;{{user.last_name}}</strong></p>
    <p>Ao desativar o usuário não poderá mais acessar o sistema, porém todo o conteúdo produzido pelo usuário será conservado.</p>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
    <a href="accounts/users/{{user.id}}/desactive/" class="waves-effect waves-green btn-flat">Desativar</a>
  </div>
</div>

<h1>{{user.first_name}}&nbsp;{{user.last_name}}</h1>
<h2>{{user}}</h2>
<h5><strong>Cadastrado em:</strong> {{user.date_joined}}</h5>
<div class="row"></div>
<h5>Documentações Criadas</h5>
{% if user.document_set.all.count %}
<div class="collection">
  {% for doc in user.document_set.all %}
  <a href="documentations/{{doc.id}}/" class="collection-item">{{doc.title}}</a>
  {% endfor %}
</div>
{% else %}
<p>Não há Documentação Registrada por esse usuário.</p>
{% endif %}

{% endblock content %}

app/accounts/templates/edit.html
{% extends layout %}
{% block content %}

<form method="POST">
  {% csrf_token %}

  <div class="row">
    <button type="submit" class="waves-effect waves-light btn-large col s12">
      Salvar
    </button>
  </div>

  <div class="row card-panel">
    <h5 class="col s12 center-align">Informações do Funcionário</h5>
    <div class="input-field col s12 m4">
      <input id="first_name" name="first_name" type="text" class="validate" value="{{user.first_name}}">
      <label for="first_name">Primeiro Nome</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="last_name" name="last_name" type="text" class="validate" value="{{user.last_name}}">
      <label for="last_name">Último Nome</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="email" name="email" type="text" class="validate" value="{{user.email}}">
      <label for="email">Email</label>
    </div>
  </div>
  <div class="row card-panel">
    <h5 class="col s12 center-align">Acessos do Funcionário</h5>
    <div class="input-field col s12 m4">
      <input id="username" name="username" type="text" class="validate" value="{{user.username}}">
      <label for="username">Usuário</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="password" name="password" type="password" class="validate">
      <label for="password">Senha</label>
    </div>
    <div class="input-field col s12 m4">
      <p>
        <input id="is_superuser" name="is_superuser" type="checkbox" {% if user.is_superuser %}checked{% endif %} />
        <label for="is_superuser">Super Usuário</label>
      </p>
    </div>
  </div>
</form>

{% endblock content %}

app/accounts/templates/login.html
{% extends layout %}
{% block content %}

{% if msg %}
{{msg}}
{% endif %}

<div class="valign-wrapper row login-box">
  <div class="col s12 m8 offset-m2">
    <form class="card large" method="post">
      {% csrf_token %}
      <div class="card-image">
        <img src="/static/images/login.png">
        <span class="card-title">
          <h1>
            DokSys - Sistema de Documentação
          </h1>
        </span>
      </div>
      <div class="card-content">
        <p>&nbsp;</p>
        <div class="input-field col s6">
          <input id="username" name="username" type="text" class="validate">
          <label for="username">Usuário</label>
        </div>
        <div class="input-field col s6">
          <input id="password" name="password" type="password" class="validate">
          <label for="password">Password</label>
        </div>
        <p>&nbsp;</p>
      </div>
      <div class="card-action">
        <input type="submit" value="Entrar" class="waves-effect waves-light btn-large col s12" />
        <input type="hidden" name="next" value="{{ next }}" />
      </div>
    </form>
  </div>
</div>
{% endblock content %}

app/accounts/templates/profile.html
{% extends layout %}
{% block content %}

<div class="row">
  <div class="col s6">
    <a class="waves-effect waves-light btn-large green col s12" href="accounts/profile/edit/">
      Editar Usuário
    </a>
  </div>
  <div class="col s6">
    {% if request.user.is_superuser %}
    <a class="waves-effect waves-light btn-large red col s12" href="#confirm">
      Apagar Usuário
    </a>
    {% else %}
    <a class="waves-effect waves-light btn-large red col s12" disabled>
      Apagar Usuário
    </a>
    {% endif %}
  </div>
</div>

<div id="confirm" class="modal">
  <div class="modal-content">
    <h4>Apagar Usuário</h4>
    <p>Deseja mesmo apagar o usuário:<br/><strong>{{user.first_name}}&nbsp;{{user.last_name}}</strong></p>
  </div>
  <div class="modal-footer">
    <a class="modal-action modal-close waves-effect waves-green btn-flat">Não</a>
    <a href="accounts/users/{{user.id}}/delete/" class="waves-effect waves-green btn-flat">Sim</a>
  </div>
</div>

<h1>{{user.first_name}}&nbsp;{{user.last_name}}</h1>
<h2>{{user}}</h2>
<h5><strong>Cadastrado em:</strong> {{user.date_joined}}</h5>
<div class="row"></div>
<h5>Documentações Criadas</h5>
{% if user.document_set.all.count %}
<div class="collection">
  {% for doc in user.document_set.all %}
  <a href="documentations/{{doc.id}}/" class="collection-item">{{doc.title}}</a>
  {% endfor %}
</div>
{% else %}
<p>Não há Documentação Registrada por esse usuário.</p>
{% endif %}

{% endblock content %}

app/accounts/templates/profile_edit.html
{% extends layout %}
{% block content %}

<form method="POST">
  {% csrf_token %}

  <div class="row">
    <button type="submit" class="waves-effect waves-light btn-large col s12">
      Salvar
    </button>
  </div>

  <div class="row card-panel">
    <h5 class="col s12 center-align">Informações do Funcionário</h5>
    <div class="input-field col s12 m4">
      <input id="first_name" name="first_name" type="text" class="validate" value="{{user.first_name}}">
      <label for="first_name">Primeiro Nome</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="last_name" name="last_name" type="text" class="validate" value="{{user.last_name}}">
      <label for="last_name">Último Nome</label>
    </div>
    <div class="input-field col s12 m4">
      <input id="email" name="email" type="text" class="validate" value="{{user.email}}">
      <label for="email">Email</label>
    </div>
  </div>
  <div class="row card-panel">
    <h5 class="col s12 center-align">Acessos do Funcionário</h5>
    <div class="input-field col s12 m6">
      <input id="username" name="username" type="text" class="validate" value="{{user.username}}">
      <label for="username">Usuário</label>
    </div>
    <div class="input-field col s12 m6">
      <input id="password" name="password" type="password" class="validate">
      <label for="password">Senha</label>
    </div>
  </div>
</form>

{% endblock content %}

app/accounts/templates/users.html
{% extends layout %}
{% block content %}

<h1>Lista de Usuários do Sistema</h1>

<div class="row"><a href="accounts/users/add/" class="col s12 waves-effect waves-light btn-large blue">Adicionar Novo Usuário</a></div>

<div class="collection">
  {% for user in users %}
  <a href="accounts/users/{{user.id}}/" class="collection-item">
    {% if user.is_active %}
    <span class="badge">Ativado</span>
    {% else %}
    <span class="badge">Desativado</span>
    {% endif %}
    <span class="title"><strong>Nome:</strong> {{user.first_name}} {{user.last_name}}</span>
      <p><strong>Usuário:&nbsp;</strong>{{user}}{% if user.is_superuser %} (Administrativo) {% endif %}</p>
      <p><strong>Quantidade de Documentações:&nbsp;</strong>{{user.document_set.all.count}}</p>
  </a>
  {% endfor %}
</div>

{% endblock content %}